# src/model_perf

# Vendor Libraries
import pandas as pd
from src.constants import OVERFITTING_THRESHOLD, METRIC_COLS
from tensorflow.keras import Sequential

# Local Libraries
from src.eda import model_performance_classification
from src.utils import show_banner, format_performance


class ModelPerformance:
    def __init__(self):
        self._title = ""
        self.data = None

    def get(self, title: str, model: Sequential, x_data: pd.DataFrame, y_data: pd.Series) -> pd.DataFrame:
        """
        Get Model Performance based on x, y data.  Sets data attribute for subsequent usage.
        :param title: Title for the performance run
        :param model: The Keras Sequential model
        :param x_data: Features for evaluation
        :param y_data: Ground truth labels
        :return: DataFrame of classification metrics
        """

        self._title = title
        self.data = model_performance_classification(model, x_data, y_data)
        return self.data

    def show(self) -> None:
        if self.data is not None:
            subtitles = format_performance(self.data)
            show_banner(f"{self._title} Model Performance", subtitles)
        else:
            raise ValueError("🚩Error: Model Performance has not been run.")

    """
    +---------------------------------------------------------------------------+
    |                               STATIC METHODS                               |
    +---------------------------------------------------------------------------+
    """

    @staticmethod
    def get_best_model_name(performance_matrix: pd.DataFrame, comparison_matrix: pd.DataFrame | None = None) -> str:
        """
        ⭐Get Best Model

        What it does:
        It identifies the "Development Champion." It looks at the models' performance during the training phase to see
        which architecture (Adam, SGD, SMOTE, etc.) handled the training-to-validation transition best.

        How it got the results: It uses the train_matrix and val_matrix generated by run_model_comparison_pipeline. These
        matrices contain metrics recorded during the training process (the .fit() stage).

        Purpose:
        It helps you detect overfitting. If a model has a perfect score in train_matrix but a poor score in
        val_matrix, best_model logic (as we refactored in model_perf.py) would flag that model as unreliable.

        :param performance_matrix: The primary DataFrame to evaluate (Validation or Test).
        :param comparison_matrix: Optional secondary DataFrame (Training) to check for overfitting.
        :return: String name of the best model.
        """

        if performance_matrix.empty:
            raise ValueError("🚩Error: Performance matrix is empty.")

        # # Actual overfitting check: calculate the gap between Training and Validation
        if comparison_matrix is not None:
            for model_name in performance_matrix.columns:
                train_f1 = comparison_matrix.loc["F1", model_name]
                val_f1 = performance_matrix.loc["F1", model_name]
                gap = train_f1 - val_f1
                
                if gap > OVERFITTING_THRESHOLD: # Threshold of 15% difference
                    print(f"⚠️ Warning: Model {model_name} is overfitting! (Gap: {gap:.2%})")

        # Find the model name with the highest F1 score
        best_model_name = performance_matrix.loc["F1"].idxmax()
        best_f1 = performance_matrix.loc["F1"].max()
        best_f1 = best_f1 * 100
        
        print(f"🏆 Best Model Identified: {best_model_name} with F1-Score: {best_f1:.4f}")
        return best_model_name

    @staticmethod
    def get_test_model_perfs(models: list) -> list:
        """
        Generates evaluation Series for all models using hold-out test data.

        :param models: List of model objects containing trained models and test data
        :return: List of pandas Series objects
        """

        test_model_perfs = []
        for test_model in models:
            test_model.model_perf.get(
                f"{test_model.title} (Test Set)",
                test_model.model,
                test_model.x_test_norm,
                test_model.y_test
            )

            # Create Model Series with the model title. This embeds the title directly inside the data object.
            test_model_series = pd.Series(
                test_model.model_perf.data.to_numpy().flatten(),
                index=METRIC_COLS,
                name=test_model.title,
            )
            test_model_perfs.append(test_model_series)

        return test_model_perfs

    @staticmethod
    def get_final_model(test_model_perfs: list, models: list):
        """
        ⭐Final Model Test

        What it does:
        It identifies the "Real-World Champion." This is the model the bank would actually put into production. It evaluates
        the models on data they have never seen before—not even during the validation tuning.

        How it got the results:
        i. The code loops through each model in your models list.
        ii. It calls test_model.model_perf.get() using the x_test_norm and y_test hold-out data.
        iii. It collects these "final exam" scores into a list called test_model_perfs.
        iv. ModelPerformance.final_model() then aggregates these scores to pick the ultimate winner based on the highest
        F1-Score on that unseen data.

        Purpose:
        This is the most honest metric. A model might "cheat" or overfit the validation data if you tune it too much, but
        it can't "cheat" the test set.

        Gets the final model that will be used for customer results based on test data.

        :param test_model_perfs: List of performance Series objects
        :param models: List of original model wrapper objects
        :return: The winning model object
        """

        # Convert the list of evaluation series into a single DataFrame for the best_model logic
        test_model_perfs_matrix = pd.concat(test_model_perfs, axis=1)

        best_model_name = ModelPerformance.get_best_model_name(test_model_perfs_matrix, comparison_matrix=None)

        # Now that we have the best model name let's return the final model
        final_model = None
        for model in models:
            if model.title == best_model_name:
                final_model = model
                break

        return final_model

    @staticmethod
    def create_comparisons(models: list) -> tuple[pd.DataFrame, pd.DataFrame]:
        """
        Creates multiple lists of comparisons (training, validation, titles, and then converts to matrices.
        :param models:
        :return:
        """

        # ❗Treat this like a private method
        def _get_matrices(model_titles: list, perfs: list) -> pd.DataFrame:
            """
            Creates a performance matrix
            :param model_titles:
            :param perfs:
            :return:
            """

            # Convert list to a single DataFrame
            perfs_matrix = pd.concat(perfs)
            perfs_matrix.index = model_titles
            perfs_matrix = perfs_matrix.T

            return perfs_matrix

        # Define comparison variables
        titles, train_perfs, val_perfs = [], [], []

        # Build model list for both performances
        for model in models:
            titles.append(model.title)
            train_perfs.append(model.train_perf)
            val_perfs.append(model.val_perf)

        # After loading all model comparisons lets get the matrices
        train_perfs_matrix = _get_matrices(titles, train_perfs)
        val_perfs_matrix = _get_matrices(titles, val_perfs)

        return train_perfs_matrix, val_perfs_matrix
